remote_theme: just-the-docs
title: "COGITO Website"


# Sidebar navigation settings
just_the_docs:
  # Enables a sidebar on all pages
  show_sidebar: true
  # Sidebar navigation
  collections:
    - pages


# Navigation links in the sidebar
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "Functionality"
    url: "/pages/functionality"
    nav_order: 2
  - title: "Workflow"
    url: "/pages/workflow"
    nav_order: 3
